#! /usr/bin/env bash

EXECUTABLE="$0"

CMANAGER=docker
IMAGENAME=hamsterpit

hamsterpit_usage () {
    cat <<EOF
Usage: $EXECUTABLE [COMMAND]

Run your coding agent of choice inside a container where it can only access the 
given project directory. The review and source control operations are assumed to
happen outside of the container.

Commands:
          build          - build an image containing the agents and dependencies
          run [PROJECT]  - run the container and give it access to the PROJECT
                           directory
          help           - show this message

EOF
}

hamsterpit_build () {
    # Save the location of the of the script - it is where the Dockerfile
    # resides.
    local scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    # Use `--no-cache` to make sure we always get the most recent
    # packages if rebuilding explicitly.
    $CMANAGER build --no-cache -t $IMAGENAME $scriptdir
}

hamsterpit_run () {
    # Build the image if it does not exist.
    $CMANAGER images -q $IMAGENAME | grep -q . || hamsterpit_build
    # Ensure state/config directories exist.
    mkdir -p .claude .gemini
    # Run the container.
    local project_path="$1"
    local container_id="$(echo -n "$project_path" | sha256sum | cut -c1-8)"
    $CMANAGER run -it --rm \
           -v "$project_path":/workspace \
           -v "$(pwd)/.gemini":/root/.gemini \
           -v "$(pwd)/.claude":/root/.claude \
           --name "hamsterpit-$container_id" \
           $IMAGENAME
}

case "$1" in
    build)
        hamsterpit_build
        ;;
    run)
        hamsterpit_run "$2"
        ;;
    *)
        hamsterpit_usage
        exit 1
        ;;
esac
